Bugfix for solaris in replwrap.bash()
Forgot to set ``echo=False`` when calling spawnu()
directly in replwrap.bash(), resulting in IOError
on SunOs:

    IOError: [Errno 22] Invalid argument: setecho() may not be called on this platform.